name: baseball
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  cupertino_icons: ^0.1.3
  date_format: ^1.0.8
  equatable: ^1.1.1
  flutter:
    sdk: flutter
  flutter_mobx: ^1.0.1
  flutter_spinkit: ^4.1.2
  http: ^0.12.0+4
  json_annotation: ^3.0.1
  meta: ^1.1.8
  mobx: ^1.0.2+1
  provider: ^4.0.4
  device_preview: ^0.3.0+1

dev_dependencies:
  build_runner: ^1.8.0
  flutter_test:
    sdk: flutter
  json_serializable: ^3.2.5
  mobx_codegen: ^1.0.2
  mockito: ^4.1.1
  pedantic: ^1.8.0+1

dependency_overrides:
  pedantic: 1.9.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/teams/
    - test/support/
  fonts:
    - family: Lato
      fonts:
        - asset: fonts/lato-regular.ttf
    - family: roboto_mono
      fonts:
        - asset: fonts/roboto_mono-regular.ttf