name: baseball
description: A small project to test the REST API located at https://statsapi.mlb.com/.
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  date_format: ^1.0.0
  equatable: ^1.2.0
  flutter:
    sdk: flutter
  flutter_mobx: ^1.1.0
  flutter_spinkit: ^4.1.0
  http: ^0.12.0
  json_annotation: ^3.0.0
  mobx: ^1.1.0
  provider: ^4.0.0
  device_preview: ^0.4.0

dev_dependencies:
  build_runner: ^1.8.0
  flutter_test:
    sdk: flutter
  json_serializable: ^3.3.0
  mobx_codegen: ^1.0.0
  mockito: ^4.1.0
  pedantic: ^1.8.0

dependency_overrides:
  pedantic: 1.9.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/teams/
    - test/support/
  fonts:
    - family: Lato
      fonts:
        - asset: fonts/lato-regular.ttf
    - family: roboto_mono
      fonts:
        - asset: fonts/roboto_mono-regular.ttf